apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-4ch-ingress
  namespace: default
spec:
  ingressClassName: "gce"
  rules:
  - host: "hello-4ch.example.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-4ch
            port:
              number: 8080