name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Checkout do c√≥digo
    - name: Checkout code
      uses: actions/checkout@v3
    
    # 2. Autenticar no GCP usando chave JSON
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    # 3. Setup do gcloud CLI
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    
    # 4. Deploy no Cloud Run
    #Por conta do "source ." eu fico sem precisar buildar, push ou artifct
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy hello-4ch \
          --source . \
          --region=us-east1 \
          --allow-unauthenticated \
          --project=${{ secrets.GCP_PROJECT_ID }}